// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tutorial

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Age  sql.NullInt32
	Bio  sql.NullString
}
