services:
  db:
    image: postgres:15
    container_name: "postgres"
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      POSTGRES_INITDB_ARGS: --encoding=utf-8
      PGOPTIONS: --search_path=public